version: "1"
services:
  backend:
    image: backend:v1
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - ./backend/app/.docker.env:/app/.env
    networks:
      - fortytwo
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    image: frontend:v1
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./frontend/app/.docker.env:/app/.env
      - /app/node_modules
      - ./frontend/app:/app
    networks:
      - fortytwo
    ports:
      - 3001:3001
    depends_on:
      - database
      - backend

  database:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - fortytwo

networks:
  fortytwo:
